---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.0.1
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_STORE_URI
          value: "sqlite:///mlflow.db"
        - name: DEFAULT_ARTIFACT_ROOT
          value: "./mlruns"
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
